### ISSUE TITLE
Whitelist system improvements | Players with immune privileges

### ISSUE THREAD

**Issue by crashzk** [ratawar/profile-status#1]
It could automatically let players with immune privileges check the plugin.

That is, you have privileges to enter the server without going through the checks, but when you lose the privileges you must have the requirements to enter the server.

**Comment by maxijabase** [comment]
I believe this already happens by adding or removing a player from the whitelist?
Do you suggest a flag that whether it is given to a player, the plugin performs the checks?

**Comment by crashzk** [comment]
> I believe this already happens by adding or removing a player from the whitelist?
> Do you suggest a flag that whether it is given to a player, the plugin performs the checks?

That, plugin itself already has this option, however the player has to be added manually by an admin.

What I would like is that if the player already has privileges he is immune to the plugin's checks. That is, a player who was unable to connect because of not having the minimum hours in the game, if he receives privileges he can enter even if he does not have the minimum hours, he would be immune to the plugin's checks.

It is worth remembering that it would be just the checks of the Check Hours module of the player, for the Check VAC module it would be another cvar to control.

Example of what I am saying:
- `sm_vacbans_immunity` - ADMFLAG_ROOT
- `sm_hours_immunity` - ADMFLAG_ROOT
- `sm_levels_immunity` - ADMFLAG_ROOT

In this case players with ROOT access on the server were able to connect without going through the Hours check or VAC Bans.

Did you understand more or less?

**[EDIT]**
Remembering, it would just be immunity for the player with Root access in this case, if he loses his privileges he goes through the checks, if he doesn't have the requirements, the entry on the server is denied.

**Comment by crashzk** [comment]
Any news about this feature? Is it possible to implement it?

**Comment by maxijabase** [comment]
> Any news about this feature? Is it possible to implement it?

I haven't touched the code in a long while to work on its features and I'm not sure if this is a feature I'm interested in implementing since there already is one that does that, implementing a new way of bypassing the checks is being redundant, in my opinion.

**Comment by crashzk** [comment]
Currently I agree to tell you the truth, I really needed it due to the error when sending the command to add directly from the server console, reported in this issues #9, but as it was corrected I think I don't need this feature anymore. It is that I currently manage a network of csgo servers, it is true that I do not even enter them, I do everything from the console.

This suggestion in this case was even more of an automatic way to add and remove access for players who do not have the requirements. Let's say that a player does not have the requirements, however it has the privilege of reserved slot on the server, **flag "a"**, with these cvars:
```
sm_vacbans_immunity
sm_hours_immunity
sm_levels_immunity
```
Player would be immune to the checks, however if he loses the reserved slot privilege, be removed in the case, he is no longer able to enter the server since he does not have the requirements.

Command `sm_ps` would leave just in case you want to release permanent let's say, even if you do not have privileges as it was added by the command it enters without a problem, stays on the whitelist.

Anyway, it is up to you, I believe that these improvements are welcome, but it can be done further.
