### ISSUE TITLE
Translation file errors

### ISSUE THREAD

**Issue by crashzk** [ratawar/profile-status#10]
There are some errors, or information missing from the translation files.

- Gray colors are misspelled, they have to be  `grey`, if not in CSGO it doesn't work.
https://github.com/ratawar/profile-status/blob/eaeb52c817feefae1f11633c920ed98b4d429499/scripting/include/multicolors/colors.inc#L33
Missing information in:
```
"Command Generic Usage"
	{
		"en" "{green}[PS]{default} Usage: sm_ps <hours|bans> <add|remove|check> <STEAMID64>"
		"es" "{green}[PS]{default} Uso: sm_ps <add|remove|check> <STEAMID64>"
		"pt" "{green}[PS]{default} Uso: sm_ps <add|remove|check> <STEAMID64>"
	}
```

**Comment by maxijabase** [comment]
Did you try this modification with successful outcomes?

**Comment by crashzk** [comment]
> Did you try this modification with successful outcomes?

Everything working, colors ok now.
