### ISSUE TITLE
Hours check bug

### ISSUE THREAD

**Issue by shubhamdev8** [ratawar/profile-status#12]
i have disabled hours check in config but the plugin still kicks players with this error
device<35><STEAM_1:1:227327333><>" disconnected (reason "Error while retrieving your hours! Make sure they're public"
also the player"s profile is already public

**Comment by maxijabase** [comment]
![image](https://user-images.githubusercontent.com/20617661/87232743-cb821780-c397-11ea-8cdb-26715b94e36b.png)
That is incorrect, the message doesn't say the profile isn't public, the message says **his hours** aren't public.
Can you send your ProfileStatus file to see exactly how you disabled the hour check? Also, what version of the plugin are you using?

**Comment by shubhamdev8** [comment]
ok so his hours aren't public but why does it checks for hours when i have disabled it
here is the config
`// This file was auto-generated by AutoExecConfig read and append beta
// ConVars for plugin "profilestatus.smx"


// Enable the plugin?
// -
// Default: "1"
// Minimum: "0.000000"
// Maximum: "1.000000"
sm_profilestatus_enable "1"

// Your Steam API key (https://steamcommunity.com/dev/apikey)
// -
// Default: ""
sm_profilestatus_apikey "ADEC8B67783289F5D3CXXXXXXXXXXX"

// Database name. Change this value only if you're using another database set in databases.cfg
// -
// Default: "storage-local"
sm_profilestatus_database "storage-local"

// Enable Hour Checking functions?
// -
// Default: "1"
// Minimum: "0.000000"
// Maximum: "1.000000"
sm_profilestatus_hours_enable "0"

// Minimum of hours requiered to enter the server.
// -
// Default: ""
sm_profilestatus_hours_minhours ""

// Enable Hours Check Whitelist?
// -
// Default: "1"
sm_profilestatus_hours_whitelist_enable "1"

// Whitelist members that have been checked automatically?
// -
// Default: "1"
// Minimum: "0.000000"
// Maximum: "1.000000"
sm_profilestatus_hours_whitelist_auto "1"

// Enable Ban Checking functions?
// -
// Default: "1"
// Minimum: "0.000000"
// Maximum: "1.000000"
sm_profilestatus_bans_enable "1"

// Enable Bans Whitelist?
// -
// Default: "1"
// Minimum: "0.000000"
// Maximum: "1.000000"
sm_profilestatus_bans_whitelist "1"

// Minimum days since the last VAC ban to be allowed into the server (0 for zero tolerance).
// -
// Default: "0"
sm_profilestatus_vac_days "0"

// Amount of VAC bans tolerated until prohibition (0 for zero tolerance).
// -
// Default: "0"
sm_profilestatus_vac_amount "0"

// 0- Don't kick if there's a community ban | 1- Kick if there's a community ban
// -
// Default: "0"
sm_profilestatus_community_ban "0"

// Amount of game bans tolerated until prohibition (0 for zero tolerance).
// -
// Default: "5"
sm_profilestatus_game_bans "2"

// 0- Don't check for economy bans | 1- Kick if user is economy "banned" only. | 2- Kick if user is in either "banned" or "probation" state.
// -
// Default: "0"
// Minimum: "0.000000"
// Maximum: "2.000000"
sm_profilestatus_economy_bans "0"

// Enable Steam Level Checking functions
// -
// Default: "1"
// Minimum: "0.000000"
// Maximum: "1.000000"
sm_profilestatus_level_enable "1"

// Enable Steam Level Check Whitelist?
// -
// Default: "1"
// Minimum: "0.000000"
// Maximum: "1.000000"
sm_profilestatus_level_whitelist_enable "1"

// Whitelist members that have been checked automatically?
// -
// Default: "1"
// Minimum: "0.000000"
// Maximum: "1.000000"
sm_profilestatus_level_whitelist_auto "1"

// Minimum level required to enter the server.
// -
// Default: ""
sm_profilestatus_minlevel "1"

// Maximum level tolerated to enter the server (can be left blank for no maximum).
// -
// Default: ""
sm_profilestatus_maxlevel ""

// Block Fully Private Profiles?
// -
// Default: "1"
// Minimum: "0.000000"
// Maximum: "1.000000"
sm_profilestatus_privateprofile_enable "1"
`
plugin version is 2.3.3

**Comment by ErikMinekus** [comment]
It's caused by these if statements: https://github.com/ratawar/profile-status/blob/master/scripting/profilestatus.sp#L1024-L1047

They're checking if the convar handles are valid (which they always are), instead of retrieving the boolean value.

**Comment by maxijabase** [comment]
Thank you a lot for the heads up @ErikMinekus, I'll be shipping an update today fixing these various bugs. Apologies for the inactivity, life has been wild lately.
