### ISSUE TITLE
Implement option to separate servers in the database | server_id

### ISSUE THREAD

**Issue by crashzk** [ratawar/profile-status#15]
Implement the option to separate the servers in the database.

Currently I have several servers focused on casual and others competitive. Casual servers put that at least 45 hours in the game to enter and in competitive servers 110 hours in the game to enter.

Then start the problem, if the player does not have 110 hours in the game to enter the competitive servers, but he already has 45 hours to enter the casual servers, if he enters a casual server he is added to the database and with that he can enter then on competitive servers even without having 110 hours.

The solution would be to implement some way of separating the servers within the database, something like `server_id` is the same as in SourceBans++.

AI would configure each server with an ID and check only that server on the whitelist.

Was that possible?

**Comment by maxijabase** [comment]
Will study the possibility of implementing this, thanks

**Comment by crashzk** [comment]
What's new about this feature?

**Comment by maxijabase** [comment]
Completely disconnected myself from this project and focused on IRL work and more advanced projects. Just got reminded of this and will probably make an update soon. Sorry about that.

**Comment by crashzk** [comment]
Oops, sorry to bother with it again, is that I would really be grateful with this implementation to be able to apply it on my servers.

 Would you have any news, got some time to check?

**Comment by maxijabase** [comment]
I'm fully aware of this but as I said, I have work responsibilities. There's no ETA for this feature.

**Comment by abnerfs** [comment]
Hi, thanks for the plugin, awesome work btw. I'm willing to work on this feature and submit a PR, would you have ETA to review it?

**Comment by maxijabase** [comment]
> Hi, thanks for the plugin, awesome work btw. I'm willing to work on this feature and submit a PR, would you have ETA to review it?

Hello, thank you. Yes that'd be much quicker. Contact me on Discord (ampere#4645), I can hand you some advances related to that, as well as an unfinished port to ripext.

**Comment by abnerfs** [comment]
I've sent you a friend request

**Comment by crashzk** [comment]
Hello, I don't know if it would be the same thing, but I thought in another way, I believe it is easier to identify each server.

Instead of separating the servers by **`server_id`** put a cvar so that we can choose the name of the table in the database.

Atualmente ele criar as tabelas normalmente no banco de dados:
![image](https://user-images.githubusercontent.com/32937653/111525731-ae7ac100-873c-11eb-8828-31e39a9ec340.png)

Being able to choose the name of the table, I could change and use the same database for all servers, thus looking like this:
```
ps_competitivo_whitelist
ps_competitivo_whitelist_bans
ps_competitivo_level
```
```
ps_arena1v1_whitelist
ps_arena1v1_whitelist_bans
ps_arena1v1_level
```
And so on. Same database, but each server reads its table.

**Comment by maxijabase** [comment]
I took the decision of stepping down from Profile Status' development, closing this for now - it can be mentioned in the future.
