### ISSUE TITLE
Change access for players who are allowed to use the sm_ps command

### ISSUE THREAD

**Issue by crashzk** [ratawar/profile-status#2]
```
sm_ps <hours|bans> add <STEAMID64> - Add user to the whitelist. For example: !ps hours add 76561198179807307
sm_ps <hours|bans> remove <STEAMID64> - Remove a user from the whitelist. For example: !ps bans remove 76561198179807307
sm_ps <hours|bans> check <STEAMID64> - Check if a user is in the whitelist. For example: !ps hours check 76561198179807307
sm_ps whitelist - Opens whitelist menu.
```
For the player to use these commands he needs to have access to the `ADMFLAG_GENERIC` privileges, I recommend changing to`ADMFLAG_CHEATS` so it is easier to control which players have access to add players to the whitelist.

**Comment by maxijabase** [comment]
Will look into it.

**Comment by maxijabase** [comment]
It seems thanks to the integrated SourceMod permission system, you can set whatever flag you want to have permissions to use the ``sm_ps`` command. Head to **addons/sourcemod/configs/admin_overrides.cfg** and set "sm_ps" to "a" or "b" or "c", whatever flag you want to.

**Comment by crashzk** [comment]
> It seems thanks to the integrated SourceMod permission system, you can set whatever flag you want to have permissions to use the `sm_ps` command. Head to **addons/sourcemod/configs/admin_overrides.cfg** and set "sm_ps" to "a" or "b" or "c", whatever flag you want to.

Yes, in case I already use this feature. True, I thought of novice users who create servers, many of them don't even know that there are overrides in SourceMod.

Anyway, I believe that we can address this issue in the future, we will see how the community acts with this function, but we will see this further if necessary.

For now I closed Issues, thanks anyway.
