### ISSUE TITLE
Implement MySQL database support

### ISSUE THREAD

**Issue by crashzk** [ratawar/profile-status#3]
I have several servers, I wanted to make the players' time checking global.

That is, when a player is added to the database it will go on all servers.

**Comment by maxijabase** [comment]
Feature implemented in the 3.0 beta branch!
https://github.com/ratawar/profile-status/tree/development

EDIT: I just saw I forgot to upload the new files lol, MySQL support is tested and working, you'll see it in a couple days in the dev branch

**Comment by maxijabase** [comment]
I published the most recent changes in the dev branch, which includes primitive MySQL support. I don't think it's got any issues at the moment, try it out and feel free to keep reporting stuff here if anything comes up.

**Comment by crashzk** [comment]
Oops, thanks. As soon as possible I will be doing a test, any problem I will contact you again here.
