### ISSUE TITLE
Option of Checking Hours & VAC

### ISSUE THREAD

**Issue by crashzk** [ratawar/profile-status#4]
I would like to know how the plugin works with the database.

In this case, I configured to kick all players that do not have at least 120 hours, so far so good.

My question would be, after a player passes this check, is it saved in the database? Can he leave his profile private again that he is no longer kicked?

And even though his profile is private, if he takes VAC he is still kicked from the server if he tries to connect even though he has the minimum hours, correct?

**Comment by maxijabase** [comment]
Yes, a player that is in any database will not be checked (and possibly kicked) against that module's criteria in any circunstance.
VAC Bans aren't hiddable, so they will always be picked and checked by the plugin.

**Comment by crashzk** [comment]
Perfect, I will be thoroughly testing the **Checking Hours**, if after the player is saved in the database he can leave the steam profile private.

Any problems return the contact, thanks for now.
