### ISSUE TITLE
Improved Game Bans

### ISSUE THREAD

**Issue by crashzk** [ratawar/profile-status#8]
I would like to understand how this amount works, the bans that are applied in the game, on official servers steam/csgo, are registered?
```
// Amount of game bans tolerated until prohibition (0 for zero tolerance).
// -
// Default: "5"
sm_profilestatus_game_bans "5"
```
Because I didn't understand how a player can take 5 Game Bans.

And if I would have to disable this option, that is, it doesn't matter how many Game Bans it has, even then it can connect to the server.

I just want to forbid you to connect if you have a VAC Ban on your account.

**Comment by crashzk** [comment]
I believe you got this Game Bans wrong...

He would be that kind of ban, right:
![image](https://user-images.githubusercontent.com/32937653/85504308-23600680-b5c2-11ea-9353-f69a513961fb.png)

Or that ban that the player takes in the game, for example, CSGO, if I abandon a competitive match I take a temporary ban.

**Comment by maxijabase** [comment]
Game Bans are different from VAC Bans, this should be useful:
https://support.steampowered.com/kb_article.php?ref=6899-IOSK-9514
