### ISSUE TITLE
Error GetClientUserId when using commands on the server console

### ISSUE THREAD

**Issue by crashzk** [ratawar/profile-status#9]
I went to add a player to the hours whitelist to enter and showed the following error on the server console:
```
L 06/27/2020 - 14:16:37: [SM] Exception reported: Client index 0 is invalid
L 06/27/2020 - 14:16:37: [SM] Blaming: profilestatus.smx
L 06/27/2020 - 14:16:37: [SM] Call stack trace:
L 06/27/2020 - 14:16:37: [SM]   [0] GetClientUserId
L 06/27/2020 - 14:16:37: [SM]   [1] Line 875, C:\Users\Usuario\Documents\Github\profile-status\scripting\profilestatus.sp::Command
L 06/27/2020 - 14:16:37: [SM]   [2] Line 851, C:\Users\Usuario\Documents\Github\profile-status\scripting\profilestatus.sp::Command_Generic
```
I tried the command as follows `sm_ps hours add 76561198814491906`

This error happened when I tried to use it directly on the server console, I did not connect to the server to add in the case.

**[EDIT]**
I have not tested with the other options, I believe that you should check all `<hours|bans|level>` option.

**Comment by crashzk** [comment]
Using the command inside the server, everything works ok.

**Comment by maxijabase** [comment]
Executing commands from console spits an error, but the changes in the database occurs! I will work on support for executing commands from console. Sorry for the inactivity though, procrastination has been hitting hard. I will get back on track as soon as possible.

**Comment by crashzk** [comment]
> Executing commands from console spits an error, but the changes in the database occurs! I will work on support for executing commands from console. Sorry for the inactivity though, procrastination has been hitting hard. I will get back on track as soon as possible.

So, I used it on the console, but even then the player I added on the whitelist was unable to connect, only after I logged in to the server and put the command through the chat / console that he managed to enter.

**Comment by crashzk** [comment]
@ratawar this issue was closed but the BUG continues:
```
L 08/01/2020 - 22:44:02: [SM] Exception reported: Client index 0 is invalid
L 08/01/2020 - 22:44:02: [SM] Blaming: profilestatus.smx
L 08/01/2020 - 22:44:02: [SM] Call stack trace:
L 08/01/2020 - 22:44:02: [SM]   [0] GetClientUserId
L 08/01/2020 - 22:44:02: [SM]   [1] Line 874, C:\Users\Usuario\Documents\Github\profile-status\scripting\profilestatus.sp::Command
L 08/01/2020 - 22:44:02: [SM]   [2] Line 850, C:\Users\Usuario\Documents\Github\profile-status\scripting\profilestatus.sp::Command_Generic
```
And the player is not added to the whitelist. I can only add the player to the whitelist if I am connected to the server, console, RCON command is not possible.

I have the latest version of the plugin: ` "[ANY] Profile Status" (2.3.4) by ratawar`

**Comment by maxijabase** [comment]
> @ratawar this issue was closed but the BUG continues:
> 
> ```
> L 08/01/2020 - 22:44:02: [SM] Exception reported: Client index 0 is invalid
> L 08/01/2020 - 22:44:02: [SM] Blaming: profilestatus.smx
> L 08/01/2020 - 22:44:02: [SM] Call stack trace:
> L 08/01/2020 - 22:44:02: [SM]   [0] GetClientUserId
> L 08/01/2020 - 22:44:02: [SM]   [1] Line 874, C:\Users\Usuario\Documents\Github\profile-status\scripting\profilestatus.sp::Command
> L 08/01/2020 - 22:44:02: [SM]   [2] Line 850, C:\Users\Usuario\Documents\Github\profile-status\scripting\profilestatus.sp::Command_Generic
> ```
> 
> And the player is not added to the whitelist. I can only add the player to the whitelist if I am connected to the server, console, RCON command is not possible.
> 
> I have the latest version of the plugin: ` "[ANY] Profile Status" (2.3.4) by ratawar`

Releasing a fix today!

**Comment by crashzk** [comment]
Thank you, I will test.

I did a PullRequest to update some things for `Portuguese-BR` and add some information missing in the translation of some messages.
